pipeline {
  agent any
  options {
    disableConcurrentBuilds()
  }
  stages {
    stage('Build') {
        steps {
            sh 'wget https://api.zubr.in/content.zip -O content.zip'
            sh 'unzip -q -o content.zip -d content/'
            sh 'hugo --cacheDir $WORKSPACE/cache'
        }
    }
    stage('Deploy') {
        environment {
            FRONTEND_HOST  = credentials('FRONTEND_HOST')
        }
        steps {
            writeFile file: 'hosts', text: """
$FRONTEND_HOST
"""
            ansiblePlaybook(
                  playbook: 'infrastructure/deploy.yml',
                  inventory: "hosts",
                  credentialsId: "SSH_PRIVATE_KEY",
                  hostKeyChecking: false
            )
        }
    }
  }
}
