pipeline {
  agent any
  options {
    disableConcurrentBuilds()
  }
  stages {
    stage('Build') {
        steps {
            sh 'wget https://api.zubr.in/content.zip -O content.zip'
            sh 'unzip -q content.zip -d content/'
            sh 'hugo --cacheDir ${WORKSPACE}'
        }
    }
  }
}
