pipeline {
  agent any
  options {
    disableConcurrentBuilds()
  }
  stages {
    stage('Build') {
        steps {
            sh 'wget https://api.zubr.in/content.zip -O content.zip'
            sh 'unzip content.zip -q -d content/'
            sh 'hugo'
        }
    }
  }
}
